// <auto-generated />
using System;
using Infraestructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChallengeTecnicoEngee.Infraestructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230212230636_Initial Commit")]
    partial class InitialCommit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChallengeTecnicoEngee.Domain.Entities.Empleado", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SectorId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SectorId");

                    b.ToTable("Empleados");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Activo = true,
                            Apellidos = "de Almeida",
                            FechaAlta = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Daniel",
                            SectorId = 2L
                        },
                        new
                        {
                            Id = 2L,
                            Activo = true,
                            Apellidos = "Riva",
                            FechaAlta = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Dario",
                            SectorId = 1L
                        },
                        new
                        {
                            Id = 3L,
                            Activo = true,
                            Apellidos = "Pellegrini",
                            FechaAlta = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Diego",
                            SectorId = 3L
                        },
                        new
                        {
                            Id = 4L,
                            Activo = true,
                            Apellidos = "Musso",
                            FechaAlta = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Federico",
                            SectorId = 2L
                        },
                        new
                        {
                            Id = 5L,
                            Activo = true,
                            Apellidos = "Rodriguez",
                            FechaAlta = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Laura",
                            SectorId = 1L
                        },
                        new
                        {
                            Id = 6L,
                            Activo = true,
                            Apellidos = "Basanta",
                            FechaAlta = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Lautaro Ariel",
                            SectorId = 3L
                        },
                        new
                        {
                            Id = 7L,
                            Activo = true,
                            Apellidos = "Castello",
                            FechaAlta = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Manuel",
                            SectorId = 2L
                        },
                        new
                        {
                            Id = 8L,
                            Activo = true,
                            Apellidos = "Barrios",
                            FechaAlta = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Paula",
                            SectorId = 1L
                        },
                        new
                        {
                            Id = 9L,
                            Activo = true,
                            Apellidos = "Diaz",
                            FechaAlta = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Rocio",
                            SectorId = 3L
                        },
                        new
                        {
                            Id = 10L,
                            Activo = true,
                            Apellidos = "Parasis",
                            FechaAlta = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Sebastian",
                            SectorId = 2L
                        },
                        new
                        {
                            Id = 11L,
                            Activo = true,
                            Apellidos = "Marcote",
                            FechaAlta = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Walter",
                            SectorId = 1L
                        },
                        new
                        {
                            Id = 12L,
                            Activo = true,
                            Apellidos = "Balcarcel",
                            FechaAlta = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Guillermo",
                            SectorId = 3L
                        },
                        new
                        {
                            Id = 13L,
                            Activo = true,
                            Apellidos = "Gawron",
                            FechaAlta = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Esteban",
                            SectorId = 2L
                        },
                        new
                        {
                            Id = 14L,
                            Activo = true,
                            Apellidos = "Peddini",
                            FechaAlta = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Enzo",
                            SectorId = 2L
                        },
                        new
                        {
                            Id = 15L,
                            Activo = true,
                            Apellidos = "Russo",
                            FechaAlta = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Andrea",
                            SectorId = 3L
                        },
                        new
                        {
                            Id = 16L,
                            Activo = true,
                            Apellidos = "Zarate",
                            FechaAlta = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Adrian",
                            SectorId = 2L
                        },
                        new
                        {
                            Id = 17L,
                            Activo = true,
                            Apellidos = "Yune",
                            FechaAlta = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Melisa",
                            SectorId = 1L
                        },
                        new
                        {
                            Id = 18L,
                            Activo = true,
                            Apellidos = "Russmann",
                            FechaAlta = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Nicolas",
                            SectorId = 3L
                        },
                        new
                        {
                            Id = 19L,
                            Activo = true,
                            Apellidos = "Trillo",
                            FechaAlta = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Galo",
                            SectorId = 2L
                        },
                        new
                        {
                            Id = 20L,
                            Activo = true,
                            Apellidos = "Pellegrini",
                            FechaAlta = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Diego",
                            SectorId = 1L
                        },
                        new
                        {
                            Id = 21L,
                            Activo = true,
                            Apellidos = "Lupercal",
                            FechaAlta = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Horus, 'El Architraidor'",
                            SectorId = 4L
                        },
                        new
                        {
                            Id = 22L,
                            Activo = true,
                            Apellidos = "Russ",
                            FechaAlta = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Leman, 'El Rey Lobo'",
                            SectorId = 4L
                        },
                        new
                        {
                            Id = 23L,
                            Activo = true,
                            Apellidos = "Guilliman",
                            FechaAlta = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Robute, 'El Maestro de Ultramar'",
                            SectorId = 4L
                        },
                        new
                        {
                            Id = 24L,
                            Activo = true,
                            Apellidos = "El'Jhonson",
                            FechaAlta = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Lion, 'La Bestia'",
                            SectorId = 4L
                        });
                });

            modelBuilder.Entity("ChallengeTecnicoEngee.Domain.Entities.Sector", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Sectores");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Activo = true,
                            Codigo = "QA",
                            Descripcion = "Quality Assurance",
                            FechaAlta = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2L,
                            Activo = true,
                            Codigo = "RRHH",
                            Descripcion = "Recursos Humanos",
                            FechaAlta = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3L,
                            Activo = true,
                            Codigo = "COMME",
                            Descripcion = "Comercial",
                            FechaAlta = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4L,
                            Activo = true,
                            Codigo = "HQ",
                            Descripcion = "Gerencia",
                            FechaAlta = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Domain.Entities.LogVisita", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("ApellidosVisitante")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("EmpleadoVisitadoId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaHoraIngreso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombresVisitante")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("NumeroDocumentoVisitante")
                        .IsRequired()
                        .HasColumnType("bigint");

                    b.Property<string>("NumeroTarjetaIngreso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SectorId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoVisitadoId");

                    b.HasIndex("SectorId");

                    b.ToTable("LogsVisitas");
                });

            modelBuilder.Entity("ChallengeTecnicoEngee.Domain.Entities.Empleado", b =>
                {
                    b.HasOne("ChallengeTecnicoEngee.Domain.Entities.Sector", "Sector")
                        .WithMany("Empleados")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("Domain.Entities.LogVisita", b =>
                {
                    b.HasOne("ChallengeTecnicoEngee.Domain.Entities.Empleado", "EmpleadoVisitado")
                        .WithMany()
                        .HasForeignKey("EmpleadoVisitadoId");

                    b.HasOne("ChallengeTecnicoEngee.Domain.Entities.Sector", "Sector")
                        .WithMany()
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EmpleadoVisitado");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("ChallengeTecnicoEngee.Domain.Entities.Sector", b =>
                {
                    b.Navigation("Empleados");
                });
#pragma warning restore 612, 618
        }
    }
}
